version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  # You can adjust the runtime version based on your requirements
    commands:
      - apt-get update
      - apt-get install -y unzip
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
      - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - apt-get update && apt-get install -y terraform

  pre_build:
    commands:
      - terraform --version
      - terraform init

  build:
    commands:
      - terraform validate  # Optional: Validate Terraform configuration
      - terraform plan -out=tfplan  # Generate an execution plan
      - terraform apply -auto-approve tfplan  # Apply the generated plan automatically

  post_build:
    commands:
      - echo "Terraform deployment completed on $(date)"
